//lista de livros
GET http://localhost:3333/livro


###
//pesquisa
GET http://localhost:3333/livro?titulo=O Senhor dos Anéis&ano=1953&nota=9.5&autor=J.R.R. Tolkien&lido=true

###


POST http://localhost:3333/livro
Content-Type: application/json

{
    "titulo": "O Senhor dos Anéis",
    "autor": "J.R.R. Tolkien",
    "ano": 1953,
    "lido": false,
    "nota": 9.5
}
###


POST http://localhost:3333/livro
Content-Type: application/json

{
    "titulo": "O Senhor dos Anéis",
    "autor": "J.R.R. Tolkien",
    "ano": 1953,
    "lido": true,
    "nota": 9.5
}


###

put http://localhost:3333/livro/
Content-Type: application/json

{
    "titulo": "O Senhor dos Anéis",
    "autor": "J.R.R. Tolkien",
    "ano": 1953,
    "lido": false,
    "nota": 9.5
}

###

DELETE http://localhost:3333/livro/